services:
  # BACKEND (Spring Boot)
  - type: web
    name: iprwc-api
    env: java
    rootDir: backend
    buildCommand: ./mvnw -DskipTests clean package
    startCommand: java -Dserver.port=$PORT -jar target/*.jar
    plan: free
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://dpg-d3og751r0fns73c6nna0-a.frankfurt-postgres.render.com:5432/pcparts?sslmode=require
      - key: SPRING_DATASOURCE_USERNAME
        value: pcparts_user
      - key: SPRING_DATASOURCE_PASSWORD
        value: 1CRmONxut79FQbeHCOMFueGSxwCiDrnl
      - key: CORS_ALLOWED_ORIGINS
        value: https://iprwc-frontend.onrender.com

  # FRONTEND (Angular)
  - type: static
    name: iprwc-frontend
    rootDir: frontend
    buildCommand: npm ci && npm run build -- --configuration production
    publishPath: dist/pcparts-frontend
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
