services:
  - type: web
    name: iprwc-api
    env: docker
    rootDir: backend       # or path where Dockerfile sits
    dockerfilePath: Dockerfile   # if in that folder
    plan: free
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://dpg-d3og751r0fns73c6nna0-a.frankfurt-postgres.render.com:5432/pcparts?sslmode=require
      - key: SPRING_DATASOURCE_USERNAME
        value: pcparts_user
      - key: SPRING_DATASOURCE_PASSWORD
        value: 1CRmONxut79FQbeHCOMFueGSxwCiDrnl
      - key: CORS_ALLOWED_ORIGINS
        value: https://iprwc-frontend.onrender.com
